name: PR Test Build

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pr-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build-steps.yml
